[theme]
primaryColor = "#4CAF50"  # Green for primary elements
backgroundColor = "#FFFFFF"  # White background
secondaryBackgroundColor = "#F0F2F6"  # Light gray for widgets
textColor = "#1E3D59"  # Dark blue for readability
font = "sans serif"

# Custom button color override
[theme.button]
backgroundColor = "#FFFFFF"  # White button background
textColor = "#4CAF50"  # Green text for buttons
